FROM ubuntu:24.04

# Update package list and install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Deno
RUN curl -fsSL https://deno.land/install.sh | sh

ENV DENO_INSTALL="/root/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"

# Install global dependencies
# RUN deno i -g npm:concurrently

WORKDIR /app

CMD ["sh", "-c", "deno install --allow-scripts && deno task dev"]
